channels:
  - conda-forge
dependencies:
  - netcdf4
  - pytorch::pytorch
  - matplotlib
  - dask
  - bottleneck
  - seaborn
  - jupyter
  - cdo
  - cartopy
  - xarray
  - python=3.7
  - python-cdo
  - hdf5
  - cmocean
  - rasterio
  - tqdm
  - scikit-learn
